sns:
  label: 社交资料
  items:
    rss:
      name: rss
      label: RSS
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    weibo:
      name: weibo
      label: 微博
      type: text
      placeholder: '只需填入微博 Id 即可'
    email:
      name: email
      label: Email
      type: text
      placeholder: '只需填入邮箱地址即可'
    github:
      name: github
      label: Github
      type: text
      placeholder: '只需填入 Github 用户名即可'
    qq:
      name: qq
      label: QQ
      type: text
      placeholder: '只需填入 QQ 号即可'
    telegram:
      name: telegram
      label: Telegram
      type: text
      placeholder: '只需填入 Telegram Id 即可'
style:
  label: 样式设置
  items:
    scrollbar:
      name: scrollbar
      label: 全局滚动条颜色
      type: color
      default: '#3798e8'
    code_pretty:
      name: code_pretty
      label: 文章代码高亮主题
      type: select
      default: ''
      options:
        - value: ''
          label: '无'
        - value: '-solarizedlight'
          label: 'Solarized Light'
        - value: '-tomorrow'
          label: 'Tomorrow'
